# Setup
title:               3 Line Maps
tagline:             ''
description:         'Good maps'
url:                 https://3LineMaps.com
baseurl:             ''
paginate:            5
permalink:           pretty
destination:        ./tmp/_site/www

# About/contact
author:
  name:              ePi Rational, Inc.
  url:               https://3LineMaps.com
  email:             3LineMaps@RobLabs.com

# Gems
plugins:
  - jekyll-redirect-from
  - jekyll-paginate

# Custom vars
version:             1.1.278
# google_analytics_id: #UA-XXXX-Y
